trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:

- stage: Deploy
  jobs:
  - job: Deploy
    displayName: 'Deploy changed section to OVH files server'
    condition: eq(variables['Build.Reason'], 'IndividualCI')
    steps:

    - template: copy-files-to-ovh.yaml
      parameters:
        folder: 'images'

    - template: copy-files-to-ovh.yaml
      parameters:
        folder: 'user/pages'

    - template: copy-files-to-ovh.yaml
      parameters:
        folder: 'user/themes/quark/css'

    - template: copy-files-to-ovh.yaml
      parameters:
        folder: 'user/themes/quark/templates'
